version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'docker'
    open-pull-requests-limit: 1
    rebase-strategy: auto
    target-branch: main
